name: allure-report
'on':
    push:
        branches:
            - master
jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Download Cypress
              uses: bahmutov/npm-install@v1
              env:
                  CYPRESS_INSTALL_BINARY: 0

            - name: Check Cypress cache
              run: |
                  npx cypress cache path
                  npx cypress cache list

            - name: restore / cache the binary
              id: cache-cypress
              uses: actions/cache@v1
              with:
                  path: ~/.cache/Cypress
                  key: >-
                      cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json')
                      }}

            - name: Prepare Allure history
              run: |
                  rm -r allure-results/*
                  cp -r ./allure-report/history ./allure-results/history
                  rm -r allure-report/*

            - name: Install Cypress
              run: |
                  npx cypress install
                  npx cypress cache list

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                browser: chrome
            - name: Generate Allure report
              if: always()
              uses: QuintilianoNery/action-allure-report-V2@0.2.0

            - name: Commit report results
              if: always()
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add allure-report -f
                  git add allure-results -f
                  git commit -m "[chore] autogenerate Allure report" -a
                  
            - name: Deploy to GH Pages
              run: |
                git config --global user.email ${{secrets.GITHUB_EMAIL}}
                git config --global user.name ${{secrets.GITHUB_USERNAME}}
                git remote set-url origin https://${{secrets.GITHUB_PERSONAL_TOKEN}}@github.com/saadusmani92/cypressgit.git
                npm run deploy

            - name: Push changes
              if: always()
              uses: ad-m/github-push-action@master
              with:
                  github_token: '${{ secrets.GITHUB_TOKEN }}'
                  force: true
